---
- name: web server configuration
  hosts: web
  become: yes

  roles:
    - common
    - web_server
    - security


- name: db config
  hosts: db
  become: yes

  roles:
    - common
    - security
